name              'yum-fedora'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures the Fedora Yum repositories'
version           '3.1.5'
source_url        'https://github.com/sous-chefs/yum-fedora'
issues_url        'https://github.com/sous-chefs/yum-fedora/issues'
chef_version      '>= 12.15'

supports 'fedora'
